use varmap::*;
pub trait TestTrait {
    const NAME: &'static str;
    const DESCRIPTION: &'static str;
    fn init()->Self;
    fn run_test(&mut self, count: usize);
}

pub struct Data {
    pub var_name: &'static str,
    pub var_name_hash: varmap::Key,
    pub large_str_value: &'static str,
    pub small_str_value: &'static str,
    pub enum_key: TestEnum,
}
impl Data {
    const fn new(var_name: &'static str, key: varmap::Key, large_str_value: &'static str, small_str_value: &'static str, enum_key: TestEnum) -> Self {
        Self {
            var_name,
            var_name_hash: key,
            large_str_value,
            small_str_value,
            enum_key,
        }
    }
}

#[derive(EnumVarMap,Copy,Clone,Debug)]
#[repr(u16)]
pub(crate) enum TestEnum {
    ObjectName,
    UserName,
    UserEmail,
    UserAge,
    UserCity,
    UserCountry,
    UserPhone,
    UserRole,
    UserStatus,
    UserScore,
    UserLevel,
    UserBio,
    UserAvatar,
    UserJoined,
    UserLocale,
    UserZip,
    ProductTitle,
    ProductPrice,
    ProductStock,
    ProductSku,
    ProductBrand,
    ProductCategory,
    ProductWeight,
    ProductColor,
    ProductSize,
    ProductRating,
    ProductReviews,
    ProductVendor,
    ProductWarranty,
    OrderId,
    OrderTotal,
    OrderStatus,
    OrderDate,
    OrderCustomer,
    OrderShipping,
    OrderTracking,
    OrderTax,
    OrderDiscount,
    OrderCurrency,
    OrderItems,
    DeviceModel,
    DeviceOs,
    DeviceVersion,
    DeviceBattery,
    DeviceSerial,
    DeviceVendor,
    DeviceUptime,
    DeviceMemory,
    DeviceStorage,
    DeviceCpu,
    DeviceTemp,
    ServerHost,
    ServerPort,
    ServerRegion,
    ServerUptime,
    ServerLoad,
    ServerCores,
    ServerRam,
    ServerDisk,
    ServerStatus,
    ServerKernel,
    FilePath,
    FileSize,
    FileOwner,
    FilePerms,
    FileMtime,
    FileExt,
    FileMime,
    FileHash,
    FileEncoding,
    SessionToken,
    SessionExpires,
    SessionIp,
    SessionAgent,
    SessionCreated,
    SessionActive,
    EventType,
    EventSource,
    EventPayload,
    EventSeverity,
    EventChannel,
    EventRetries,
    ConfigKey,
    ConfigValue,
    ConfigScope,
    ConfigDefault,
    ConfigEnv,
    MetricName,
    MetricValue,
    MetricUnit,
    MetricTag,
    MetricBucket,
    LogLevel,
    LogMessage,
    LogSource,
    LogTrace,
    NetworkIp,
    NetworkMac,
    NetworkGateway,
    NetworkDns,
    NetworkSubnet,
    DatabaseHost,
    DatabaseName,
    DatabaseUser,
    DatabasePool,
    DatabaseSchema,
    PaymentMethod,
    PaymentAmount,
    PaymentCurrency,
    PaymentStatus,
    AddressStreet,
    AddressCity,
    AddressState,
    AddressPostal,
    CompanyName,
    CompanyDomain,
    CompanySize,
    CompanyIndustry,
    VehicleMake,
    VehicleModel,
    VehicleYear,
    VehiclePlate,
    VehicleVin,
    BookTitle,
    BookAuthor,
    BookIsbn,
    BookPages,
    CourseTitle,
    CourseInstructor,
    CourseDuration,
    CourseDifficulty,
    TaskTitle,
    TaskPriority,
    TaskAssignee,
    TaskDeadline,
    TicketSubject,
    TicketSeverity,
    TicketReporter,
    PostTitle,
    PostAuthor,
    PostLikes,
    PostTags,
    VideoTitle,
    VideoDuration,
    VideoViews,
    VideoCodec,
    ImageWidth,
    ImageHeight,
    ImageFormat,
    ImageAlt,
    AudioTitle,
    AudioArtist,
    AudioBitrate,
    ProjectName,
    ProjectOwner,
    ProjectBudget,
    InvoiceNumber,
    InvoiceDue,
    InvoiceAmount,
    SubscriptionPlan,
    SubscriptionRenewal,
    SubscriptionPrice,
    NotificationTitle,
    NotificationBody,
    NotificationRead,
    CommentText,
    CommentAuthor,
    ReviewTitle,
    ReviewStars,
    ReviewBody,
    GameTitle,
    GameGenre,
    GamePublisher,
    GameRating,
    GamePlatform,
    MovieTitle,
    MovieDirector,
    MovieRuntime,
    MovieGenre,
    MovieYear,
    SongTitle,
    SongAlbum,
    SongGenre,
    SongYear,
    CityName,
    CityPopulation,
    CityCountry,
    CityArea,
    CityTimezone,
    CountryName,
    CountryCapital,
    CountryPopulation,
    CountryLanguage,
    CountryCurrency,
    FlightNumber,
    FlightOrigin,
    FlightDestination,
    FlightDeparture,
    FlightAirline,
    HotelName,
    HotelStars,
    HotelRooms,
    HotelCity,
    RestaurantName,
    RestaurantCuisine,
    RestaurantPrice,
    RestaurantHours,
    RecipeName,
    RecipeServings,
    RecipeTime,
    RecipeDifficulty,
    WorkoutName,
    WorkoutDuration,
    WorkoutCalories,
    WorkoutIntensity,
    PlantName,
    PlantSpecies,
    PlantWatering,
    PlantSunlight,
    AnimalName,
    AnimalSpecies,
    AnimalHabitat,
    AnimalDiet,
    PlanetName,
    PlanetMass,
    PlanetRadius,
    PlanetMoons,
    ElementSymbol,
    ElementName,
    ElementNumber,
    ElementWeight,
    LanguageName,
    LanguageSpeakers,
    LanguageFamily,
    LanguageScript,
    CurrencyCode,
    CurrencyName,
    CurrencySymbol,
    CurrencyCountry,
    RepositoryName,
    RepositoryOwner,
    RepositoryStars,
    RepositoryLanguage,
    CommitHash,
    CommitAuthor,
    CommitMessage,
    CommitDate,
    BranchName,
    BranchAhead,
    BranchBehind,
    ContactName,
    ContactPhone,
    ContactEmail,
    ContactGroup,
    ContactNotes,
    ContactFavorite,
    ContactBirthday,    
}


pub(crate) const SMALL_SET: &[Data] = &[
    Data::new("object.name", var!("object.name"), "John the greatest Rust programmer", "John", TestEnum::ObjectName),
    Data::new("user.name", var!("user.name"), "The full legal name of the user account holder", "Alice", TestEnum::UserName),
    Data::new("user.email", var!("user.email"), "The primary contact email address for the user", "a@b.co", TestEnum::UserEmail),
    Data::new("user.age", var!("user.age"), "Age of the user in years since their birth", "32", TestEnum::UserAge),
    Data::new("user.city", var!("user.city"), "The city where the user currently resides today", "Paris", TestEnum::UserCity),
    Data::new("user.country", var!("user.country"), "Country of origin or current residency of user", "France", TestEnum::UserCountry),
    Data::new("user.phone", var!("user.phone"), "Primary mobile phone number including country code", "555-0100", TestEnum::UserPhone),
    Data::new("user.role", var!("user.role"), "The assigned role or permission level of user", "admin", TestEnum::UserRole),
    Data::new("user.status", var!("user.status"), "Current account activity status of the user", "active", TestEnum::UserStatus),
    Data::new("user.score", var!("user.score"), "Reputation or trust score assigned to user", "987", TestEnum::UserScore),
    Data::new("user.level", var!("user.level"), "Experience or progression level of the user", "42", TestEnum::UserLevel),
    Data::new("user.bio", var!("user.bio"), "Short biographical text written by the user", "hi", TestEnum::UserBio),
    Data::new("user.avatar", var!("user.avatar"), "URL pointing to the user profile picture", "p.png", TestEnum::UserAvatar),
    Data::new("user.joined", var!("user.joined"), "Timestamp when user first joined the platform", "2020", TestEnum::UserJoined),
    Data::new("user.locale", var!("user.locale"), "Preferred language and region setting for user", "en-US", TestEnum::UserLocale),
    Data::new("user.zip", var!("user.zip"), "Postal or zip code for user mailing address", "10001", TestEnum::UserZip),
    Data::new("product.title", var!("product.title"), "The display title or name of the product item", "Widget", TestEnum::ProductTitle),
    Data::new("product.price", var!("product.price"), "Current retail price of the product in cents", "1999", TestEnum::ProductPrice),
    Data::new("product.stock", var!("product.stock"), "Number of units currently available in stock", "150", TestEnum::ProductStock),
    Data::new("product.sku", var!("product.sku"), "Stock keeping unit identifier for the product", "SKU-001", TestEnum::ProductSku),
    Data::new("product.brand", var!("product.brand"), "The brand or manufacturer of the product", "Acme", TestEnum::ProductBrand),
    Data::new("product.category", var!("product.category"), "Top level category this product belongs to", "tools", TestEnum::ProductCategory),
    Data::new("product.weight", var!("product.weight"), "Weight of the product measured in grams", "250", TestEnum::ProductWeight),
    Data::new("product.color", var!("product.color"), "Primary color of the product variant", "red", TestEnum::ProductColor),
    Data::new("product.size", var!("product.size"), "Physical size designation of the product", "M", TestEnum::ProductSize),
    Data::new("product.rating", var!("product.rating"), "Average customer rating from one to five", "4.5", TestEnum::ProductRating),
    Data::new("product.reviews", var!("product.reviews"), "Total number of customer reviews submitted", "1024", TestEnum::ProductReviews),
    Data::new("product.vendor", var!("product.vendor"), "Name of the third party vendor selling it", "ShopCo", TestEnum::ProductVendor),
    Data::new("product.warranty", var!("product.warranty"), "Length of warranty coverage in months", "24", TestEnum::ProductWarranty),
    Data::new("order.id", var!("order.id"), "Unique identifier assigned to this order record", "ORD-9", TestEnum::OrderId),
    Data::new("order.total", var!("order.total"), "Total amount charged for the entire order", "5000", TestEnum::OrderTotal),
    Data::new("order.status", var!("order.status"), "Current fulfillment status of the order", "shipped", TestEnum::OrderStatus),
    Data::new("order.date", var!("order.date"), "Date when the order was originally placed", "2024", TestEnum::OrderDate),
    Data::new("order.customer", var!("order.customer"), "Customer name associated with the order", "Bob", TestEnum::OrderCustomer),
    Data::new("order.shipping", var!("order.shipping"), "Selected shipping method for this order", "express", TestEnum::OrderShipping),
    Data::new("order.tracking", var!("order.tracking"), "Carrier tracking number for the shipment", "TRK123", TestEnum::OrderTracking),
    Data::new("order.tax", var!("order.tax"), "Tax amount calculated for the order", "400", TestEnum::OrderTax),
    Data::new("order.discount", var!("order.discount"), "Discount amount applied to the order", "100", TestEnum::OrderDiscount),
    Data::new("order.currency", var!("order.currency"), "Currency code used for the transaction", "USD", TestEnum::OrderCurrency),
    Data::new("order.items", var!("order.items"), "Number of distinct items in the order", "3", TestEnum::OrderItems),
    Data::new("device.model", var!("device.model"), "Manufacturer model name of the device", "Pixel", TestEnum::DeviceModel),
    Data::new("device.os", var!("device.os"), "Operating system running on the device", "Linux", TestEnum::DeviceOs),
    Data::new("device.version", var!("device.version"), "Firmware or software version of device", "1.2.3", TestEnum::DeviceVersion),
    Data::new("device.battery", var!("device.battery"), "Current battery charge percentage level", "87", TestEnum::DeviceBattery),
    Data::new("device.serial", var!("device.serial"), "Serial number printed on device chassis", "SN-001", TestEnum::DeviceSerial),
    Data::new("device.vendor", var!("device.vendor"), "Vendor or manufacturer name of device", "Google", TestEnum::DeviceVendor),
    Data::new("device.uptime", var!("device.uptime"), "Total seconds since device last booted", "3600", TestEnum::DeviceUptime),
    Data::new("device.memory", var!("device.memory"), "Installed memory capacity in megabytes", "8192", TestEnum::DeviceMemory),
    Data::new("device.storage", var!("device.storage"), "Total storage capacity in gigabytes", "256", TestEnum::DeviceStorage),
    Data::new("device.cpu", var!("device.cpu"), "Central processor model designation", "ARM", TestEnum::DeviceCpu),
    Data::new("device.temp", var!("device.temp"), "Current internal temperature in celsius", "42", TestEnum::DeviceTemp),
    Data::new("server.host", var!("server.host"), "Hostname or fully qualified domain name", "api.io", TestEnum::ServerHost),
    Data::new("server.port", var!("server.port"), "Network port number the server listens on", "8080", TestEnum::ServerPort),
    Data::new("server.region", var!("server.region"), "Geographic region where server is hosted", "us-east", TestEnum::ServerRegion),
    Data::new("server.uptime", var!("server.uptime"), "Continuous uptime duration in seconds", "99999", TestEnum::ServerUptime),
    Data::new("server.load", var!("server.load"), "Current average system load percentage", "65", TestEnum::ServerLoad),
    Data::new("server.cores", var!("server.cores"), "Number of CPU cores available on host", "16", TestEnum::ServerCores),
    Data::new("server.ram", var!("server.ram"), "Total RAM available on the server", "64GB", TestEnum::ServerRam),
    Data::new("server.disk", var!("server.disk"), "Disk space used as a percentage value", "78", TestEnum::ServerDisk),
    Data::new("server.status", var!("server.status"), "Current health status reported by server", "ok", TestEnum::ServerStatus),
    Data::new("server.kernel", var!("server.kernel"), "Linux kernel version running on host", "6.1", TestEnum::ServerKernel),
    Data::new("file.path", var!("file.path"), "Absolute filesystem path to the file resource", "/tmp/a", TestEnum::FilePath),
    Data::new("file.size", var!("file.size"), "Size of the file measured in bytes", "1024", TestEnum::FileSize),
    Data::new("file.owner", var!("file.owner"), "Username of the file system owner", "root", TestEnum::FileOwner),
    Data::new("file.perms", var!("file.perms"), "Octal permission bits set on the file", "0755", TestEnum::FilePerms),
    Data::new("file.mtime", var!("file.mtime"), "Last modification time stored on the file", "2024", TestEnum::FileMtime),
    Data::new("file.ext", var!("file.ext"), "File extension indicating the format type", "txt", TestEnum::FileExt),
    Data::new("file.mime", var!("file.mime"), "MIME type identifier for the file content", "text", TestEnum::FileMime),
    Data::new("file.hash", var!("file.hash"), "Hexadecimal hash digest of file contents", "abc123", TestEnum::FileHash),
    Data::new("file.encoding", var!("file.encoding"), "Character encoding used in the text file", "utf8", TestEnum::FileEncoding),
    Data::new("session.token", var!("session.token"), "Authentication token issued for the session", "tok-x", TestEnum::SessionToken),
    Data::new("session.expires", var!("session.expires"), "Unix timestamp when the session expires", "9999", TestEnum::SessionExpires),
    Data::new("session.ip", var!("session.ip"), "Client IP address recorded for session", "1.2.3.4", TestEnum::SessionIp),
    Data::new("session.agent", var!("session.agent"), "User agent string sent by the client", "curl", TestEnum::SessionAgent),
    Data::new("session.created", var!("session.created"), "Timestamp when this session was created", "1000", TestEnum::SessionCreated),
    Data::new("session.active", var!("session.active"), "Boolean flag whether session is active", "true", TestEnum::SessionActive),
    Data::new("event.type", var!("event.type"), "The category or type designation of event", "click", TestEnum::EventType),
    Data::new("event.source", var!("event.source"), "The originating source emitting the event", "web", TestEnum::EventSource),
    Data::new("event.payload", var!("event.payload"), "Data payload associated with the event", "{}", TestEnum::EventPayload),
    Data::new("event.severity", var!("event.severity"), "Severity level assigned to the event", "info", TestEnum::EventSeverity),
    Data::new("event.channel", var!("event.channel"), "Channel through which event was delivered", "ws", TestEnum::EventChannel),
    Data::new("event.retries", var!("event.retries"), "Number of retry attempts for the event", "0", TestEnum::EventRetries),
    Data::new("config.key", var!("config.key"), "Configuration key identifying the setting", "k1", TestEnum::ConfigKey),
    Data::new("config.value", var!("config.value"), "Stored value associated with the key", "v1", TestEnum::ConfigValue),
    Data::new("config.scope", var!("config.scope"), "Scope where this configuration applies", "global", TestEnum::ConfigScope),
    Data::new("config.default", var!("config.default"), "Default fallback value for this setting", "off", TestEnum::ConfigDefault),
    Data::new("config.env", var!("config.env"), "Environment where config is currently active", "prod", TestEnum::ConfigEnv),
    Data::new("metric.name", var!("metric.name"), "Identifier name of the recorded metric", "cpu", TestEnum::MetricName),
    Data::new("metric.value", var!("metric.value"), "Numeric value of the metric sample", "42.5", TestEnum::MetricValue),
    Data::new("metric.unit", var!("metric.unit"), "Unit of measurement for the metric", "ms", TestEnum::MetricUnit),
    Data::new("metric.tag", var!("metric.tag"), "Tag attached to the metric for grouping", "web", TestEnum::MetricTag),
    Data::new("metric.bucket", var!("metric.bucket"), "Histogram bucket the value falls into", "10", TestEnum::MetricBucket),
    Data::new("log.level", var!("log.level"), "Severity level of the log entry record", "warn", TestEnum::LogLevel),
    Data::new("log.message", var!("log.message"), "Human readable message text of the log", "oops", TestEnum::LogMessage),
    Data::new("log.source", var!("log.source"), "Source module that emitted the log", "core", TestEnum::LogSource),
    Data::new("log.trace", var!("log.trace"), "Trace identifier linking related logs", "tr-1", TestEnum::LogTrace),
    Data::new("network.ip", var!("network.ip"), "Internet protocol address of the interface", "10.0.0.1", TestEnum::NetworkIp),
    Data::new("network.mac", var!("network.mac"), "Hardware MAC address of network adapter", "AA:BB", TestEnum::NetworkMac),
    Data::new("network.gateway", var!("network.gateway"), "Default gateway address for the network", "10.0.0.1", TestEnum::NetworkGateway),
    Data::new("network.dns", var!("network.dns"), "Primary DNS resolver address used", "8.8.8.8", TestEnum::NetworkDns),
    Data::new("network.subnet", var!("network.subnet"), "Subnet mask applied to the interface", "24", TestEnum::NetworkSubnet),
    Data::new("database.host", var!("database.host"), "Database server host where it is reachable", "db.io", TestEnum::DatabaseHost),
    Data::new("database.name", var!("database.name"), "Logical name of the target database", "mydb", TestEnum::DatabaseName),
    Data::new("database.user", var!("database.user"), "Username used to authenticate to database", "dba", TestEnum::DatabaseUser),
    Data::new("database.pool", var!("database.pool"), "Maximum size of the connection pool", "20", TestEnum::DatabasePool),
    Data::new("database.schema", var!("database.schema"), "Schema namespace used inside database", "pub", TestEnum::DatabaseSchema),
    Data::new("payment.method", var!("payment.method"), "Payment instrument used by the customer", "card", TestEnum::PaymentMethod),
    Data::new("payment.amount", var!("payment.amount"), "Monetary amount charged in cents", "9999", TestEnum::PaymentAmount),
    Data::new("payment.currency", var!("payment.currency"), "Three letter ISO currency code", "EUR", TestEnum::PaymentCurrency),
    Data::new("payment.status", var!("payment.status"), "Current state of payment processing", "ok", TestEnum::PaymentStatus),
    Data::new("address.street", var!("address.street"), "Street name and number portion of address", "Main 1", TestEnum::AddressStreet),
    Data::new("address.city", var!("address.city"), "Name of the city portion of the address", "NYC", TestEnum::AddressCity),
    Data::new("address.state", var!("address.state"), "State or province portion of the address", "NY", TestEnum::AddressState),
    Data::new("address.postal", var!("address.postal"), "Postal code portion of the address", "10001", TestEnum::AddressPostal),
    Data::new("company.name", var!("company.name"), "Registered legal name of the company", "Acme", TestEnum::CompanyName),
    Data::new("company.domain", var!("company.domain"), "Primary web domain used by the company", "acme.io", TestEnum::CompanyDomain),
    Data::new("company.size", var!("company.size"), "Approximate number of employees", "500", TestEnum::CompanySize),
    Data::new("company.industry", var!("company.industry"), "Industry vertical the company operates in", "tech", TestEnum::CompanyIndustry),
    Data::new("vehicle.make", var!("vehicle.make"), "Manufacturer brand of the vehicle", "Honda", TestEnum::VehicleMake),
    Data::new("vehicle.model", var!("vehicle.model"), "Model designation of the vehicle", "Civic", TestEnum::VehicleModel),
    Data::new("vehicle.year", var!("vehicle.year"), "Model year of the vehicle production", "2020", TestEnum::VehicleYear),
    Data::new("vehicle.plate", var!("vehicle.plate"), "License plate number of the vehicle", "ABC123", TestEnum::VehiclePlate),
    Data::new("vehicle.vin", var!("vehicle.vin"), "Vehicle identification number assigned", "VIN-X", TestEnum::VehicleVin),
    Data::new("book.title", var!("book.title"), "Full title of the published book", "Rust", TestEnum::BookTitle),
    Data::new("book.author", var!("book.author"), "Primary author name of the book", "Klabnik", TestEnum::BookAuthor),
    Data::new("book.isbn", var!("book.isbn"), "ISBN identifier code for the book", "978-1", TestEnum::BookIsbn),
    Data::new("book.pages", var!("book.pages"), "Total number of pages in the book", "500", TestEnum::BookPages),
    Data::new("course.title", var!("course.title"), "Full title of the educational course", "Algo", TestEnum::CourseTitle),
    Data::new("course.instructor", var!("course.instructor"), "Name of the course primary instructor", "Tao", TestEnum::CourseInstructor),
    Data::new("course.duration", var!("course.duration"), "Total duration of the course in hours", "40", TestEnum::CourseDuration),
    Data::new("course.difficulty", var!("course.difficulty"), "Difficulty level rating of the course", "hard", TestEnum::CourseDifficulty),
    Data::new("task.title", var!("task.title"), "Short title summarizing the task work", "fix", TestEnum::TaskTitle),
    Data::new("task.priority", var!("task.priority"), "Priority designation assigned to task", "high", TestEnum::TaskPriority),
    Data::new("task.assignee", var!("task.assignee"), "Person currently assigned to the task", "ann", TestEnum::TaskAssignee),
    Data::new("task.deadline", var!("task.deadline"), "Date by which task must be completed", "2025", TestEnum::TaskDeadline),
    Data::new("ticket.subject", var!("ticket.subject"), "Brief subject line for the support ticket", "bug", TestEnum::TicketSubject),
    Data::new("ticket.severity", var!("ticket.severity"), "Severity classification of the ticket", "p1", TestEnum::TicketSeverity),
    Data::new("ticket.reporter", var!("ticket.reporter"), "User who reported the original ticket", "joe", TestEnum::TicketReporter),
    Data::new("post.title", var!("post.title"), "Display title of the published post", "Hello", TestEnum::PostTitle),
    Data::new("post.author", var!("post.author"), "Author who wrote the post content", "bob", TestEnum::PostAuthor),
    Data::new("post.likes", var!("post.likes"), "Total count of likes received by post", "42", TestEnum::PostLikes),
    Data::new("post.tags", var!("post.tags"), "Comma separated list of post tags", "rust", TestEnum::PostTags),
    Data::new("video.title", var!("video.title"), "Display title of the video content", "Demo", TestEnum::VideoTitle),
    Data::new("video.duration", var!("video.duration"), "Total duration of the video in seconds", "120", TestEnum::VideoDuration),
    Data::new("video.views", var!("video.views"), "Total view count accumulated by video", "1000", TestEnum::VideoViews),
    Data::new("video.codec", var!("video.codec"), "Video codec used for encoding stream", "h264", TestEnum::VideoCodec),
    Data::new("image.width", var!("image.width"), "Width of the image measured in pixels", "1920", TestEnum::ImageWidth),
    Data::new("image.height", var!("image.height"), "Height of the image measured in pixels", "1080", TestEnum::ImageHeight),
    Data::new("image.format", var!("image.format"), "Image format extension used to encode", "png", TestEnum::ImageFormat),
    Data::new("image.alt", var!("image.alt"), "Alternative text describing the image", "logo", TestEnum::ImageAlt),
    Data::new("audio.title", var!("audio.title"), "Title of the audio track recording", "Song", TestEnum::AudioTitle),
    Data::new("audio.artist", var!("audio.artist"), "Artist or performer of the audio", "Bach", TestEnum::AudioArtist),
    Data::new("audio.bitrate", var!("audio.bitrate"), "Bitrate of the audio stream in kbps", "320", TestEnum::AudioBitrate),
    Data::new("project.name", var!("project.name"), "Display name of the active project", "Apollo", TestEnum::ProjectName),
    Data::new("project.owner", var!("project.owner"), "Owner responsible for the project", "lead", TestEnum::ProjectOwner),
    Data::new("project.budget", var!("project.budget"), "Allocated budget for the project in usd", "50000", TestEnum::ProjectBudget),
    Data::new("invoice.number", var!("invoice.number"), "Sequential invoice number identifier", "INV-1", TestEnum::InvoiceNumber),
    Data::new("invoice.due", var!("invoice.due"), "Date when the invoice payment is due", "2025", TestEnum::InvoiceDue),
    Data::new("invoice.amount", var!("invoice.amount"), "Total amount due on the invoice", "1500", TestEnum::InvoiceAmount),
    Data::new("subscription.plan", var!("subscription.plan"), "Tier name of the subscription plan", "pro", TestEnum::SubscriptionPlan),
    Data::new("subscription.renewal", var!("subscription.renewal"), "Date when subscription renews automatically", "2025", TestEnum::SubscriptionRenewal),
    Data::new("subscription.price", var!("subscription.price"), "Monthly price of the subscription plan", "29", TestEnum::SubscriptionPrice),
    Data::new("notification.title", var!("notification.title"), "Short title displayed on notification", "alert", TestEnum::NotificationTitle),
    Data::new("notification.body", var!("notification.body"), "Body text content of the notification", "look", TestEnum::NotificationBody),
    Data::new("notification.read", var!("notification.read"), "Whether the notification has been read", "false", TestEnum::NotificationRead),
    Data::new("comment.text", var!("comment.text"), "Full text body of the user comment", "nice", TestEnum::CommentText),
    Data::new("comment.author", var!("comment.author"), "Author name attached to the comment", "kim", TestEnum::CommentAuthor),
    Data::new("review.title", var!("review.title"), "Headline title of the customer review", "good", TestEnum::ReviewTitle),
    Data::new("review.stars", var!("review.stars"), "Star rating value given in the review", "5", TestEnum::ReviewStars),
    Data::new("review.body", var!("review.body"), "Detailed body text of the customer review", "ok", TestEnum::ReviewBody),
    Data::new("game.title", var!("game.title"), "Display title of the video game release", "Tetris", TestEnum::GameTitle),
    Data::new("game.genre", var!("game.genre"), "Primary gameplay genre of the game title", "puzzle", TestEnum::GameGenre),
    Data::new("game.publisher", var!("game.publisher"), "Company publishing the game commercially", "Sega", TestEnum::GamePublisher),
    Data::new("game.rating", var!("game.rating"), "Age rating assigned to the game content", "E", TestEnum::GameRating),
    Data::new("game.platform", var!("game.platform"), "Target platform the game runs on", "PC", TestEnum::GamePlatform),
    Data::new("movie.title", var!("movie.title"), "Display title of the released motion picture", "Heat", TestEnum::MovieTitle),
    Data::new("movie.director", var!("movie.director"), "Director who directed the motion picture", "Mann", TestEnum::MovieDirector),
    Data::new("movie.runtime", var!("movie.runtime"), "Total runtime of the movie in minutes", "170", TestEnum::MovieRuntime),
    Data::new("movie.genre", var!("movie.genre"), "Primary genre classification of the movie", "crime", TestEnum::MovieGenre),
    Data::new("movie.year", var!("movie.year"), "Release year of the motion picture", "1995", TestEnum::MovieYear),
    Data::new("song.title", var!("song.title"), "Title of the recorded musical track", "Yesterday", TestEnum::SongTitle),
    Data::new("song.album", var!("song.album"), "Album on which the song appears", "Help", TestEnum::SongAlbum),
    Data::new("song.genre", var!("song.genre"), "Musical genre classification of the song", "rock", TestEnum::SongGenre),
    Data::new("song.year", var!("song.year"), "Year the song was originally released", "1965", TestEnum::SongYear),
    Data::new("city.name", var!("city.name"), "Common name of the populated city area", "Tokyo", TestEnum::CityName),
    Data::new("city.population", var!("city.population"), "Total population count of the city", "13M", TestEnum::CityPopulation),
    Data::new("city.country", var!("city.country"), "Country in which the city is located", "Japan", TestEnum::CityCountry),
    Data::new("city.area", var!("city.area"), "Geographic area of the city in km2", "2194", TestEnum::CityArea),
    Data::new("city.timezone", var!("city.timezone"), "Local timezone identifier used by city", "JST", TestEnum::CityTimezone),
    Data::new("country.name", var!("country.name"), "Common short name of the country", "Japan", TestEnum::CountryName),
    Data::new("country.capital", var!("country.capital"), "Capital city of the named country", "Tokyo", TestEnum::CountryCapital),
    Data::new("country.population", var!("country.population"), "Total population of the country", "125M", TestEnum::CountryPopulation),
    Data::new("country.language", var!("country.language"), "Primary official language of country", "ja", TestEnum::CountryLanguage),
    Data::new("country.currency", var!("country.currency"), "Official currency used in the country", "JPY", TestEnum::CountryCurrency),
    Data::new("flight.number", var!("flight.number"), "Flight number identifier assigned by carrier", "AA100", TestEnum::FlightNumber),
    Data::new("flight.origin", var!("flight.origin"), "Origin airport code for the flight", "JFK", TestEnum::FlightOrigin),
    Data::new("flight.destination", var!("flight.destination"), "Destination airport code for the flight", "LAX", TestEnum::FlightDestination),
    Data::new("flight.departure", var!("flight.departure"), "Scheduled departure time for the flight", "08:00", TestEnum::FlightDeparture),
    Data::new("flight.airline", var!("flight.airline"), "Operating airline carrier of the flight", "AA", TestEnum::FlightAirline),
    Data::new("hotel.name", var!("hotel.name"), "Display name of the hotel property", "Hilton", TestEnum::HotelName),
    Data::new("hotel.stars", var!("hotel.stars"), "Star rating assigned to the hotel", "5", TestEnum::HotelStars),
    Data::new("hotel.rooms", var!("hotel.rooms"), "Total number of rooms in the hotel", "200", TestEnum::HotelRooms),
    Data::new("hotel.city", var!("hotel.city"), "City in which the hotel is located", "Rome", TestEnum::HotelCity),
    Data::new("restaurant.name", var!("restaurant.name"), "Display name of the restaurant venue", "Nobu", TestEnum::RestaurantName),
    Data::new("restaurant.cuisine", var!("restaurant.cuisine"), "Primary cuisine style served at venue", "sushi", TestEnum::RestaurantCuisine),
    Data::new("restaurant.price", var!("restaurant.price"), "Average price range per person served", "$$$", TestEnum::RestaurantPrice),
    Data::new("restaurant.hours", var!("restaurant.hours"), "Operating hours of the restaurant venue", "9-22", TestEnum::RestaurantHours),
    Data::new("recipe.name", var!("recipe.name"), "Display name of the prepared dish", "Pizza", TestEnum::RecipeName),
    Data::new("recipe.servings", var!("recipe.servings"), "Number of servings produced by recipe", "4", TestEnum::RecipeServings),
    Data::new("recipe.time", var!("recipe.time"), "Total time required to prepare recipe", "30m", TestEnum::RecipeTime),
    Data::new("recipe.difficulty", var!("recipe.difficulty"), "Difficulty level of preparing the recipe", "easy", TestEnum::RecipeDifficulty),
    Data::new("workout.name", var!("workout.name"), "Display name of the workout routine", "Squats", TestEnum::WorkoutName),
    Data::new("workout.duration", var!("workout.duration"), "Total duration of the workout in minutes", "45", TestEnum::WorkoutDuration),
    Data::new("workout.calories", var!("workout.calories"), "Estimated calories burned during workout", "300", TestEnum::WorkoutCalories),
    Data::new("workout.intensity", var!("workout.intensity"), "Intensity level of the workout session", "high", TestEnum::WorkoutIntensity),
    Data::new("plant.name", var!("plant.name"), "Common name of the plant species", "Cactus", TestEnum::PlantName),
    Data::new("plant.species", var!("plant.species"), "Scientific species name of the plant", "Cact", TestEnum::PlantSpecies),
    Data::new("plant.watering", var!("plant.watering"), "Watering frequency required by the plant", "weekly", TestEnum::PlantWatering),
    Data::new("plant.sunlight", var!("plant.sunlight"), "Sunlight exposure requirement for plant", "full", TestEnum::PlantSunlight),
    Data::new("animal.name", var!("animal.name"), "Common name of the animal species", "Cat", TestEnum::AnimalName),
    Data::new("animal.species", var!("animal.species"), "Scientific species name of the animal", "Felis", TestEnum::AnimalSpecies),
    Data::new("animal.habitat", var!("animal.habitat"), "Natural habitat where animal is found", "home", TestEnum::AnimalHabitat),
    Data::new("animal.diet", var!("animal.diet"), "Primary dietary classification of animal", "carn", TestEnum::AnimalDiet),
    Data::new("planet.name", var!("planet.name"), "Common name of the planet body", "Earth", TestEnum::PlanetName),
    Data::new("planet.mass", var!("planet.mass"), "Total mass of the planet in kg", "6e24", TestEnum::PlanetMass),
    Data::new("planet.radius", var!("planet.radius"), "Equatorial radius of the planet in km", "6371", TestEnum::PlanetRadius),
    Data::new("planet.moons", var!("planet.moons"), "Number of natural moons orbiting planet", "1", TestEnum::PlanetMoons),
    Data::new("element.symbol", var!("element.symbol"), "Chemical symbol of the element", "H", TestEnum::ElementSymbol),
    Data::new("element.name", var!("element.name"), "Common name of the chemical element", "Hydro", TestEnum::ElementName),
    Data::new("element.number", var!("element.number"), "Atomic number of the chemical element", "1", TestEnum::ElementNumber),
    Data::new("element.weight", var!("element.weight"), "Standard atomic weight of the element", "1.008", TestEnum::ElementWeight),
    Data::new("language.name", var!("language.name"), "Common name of the spoken language", "Rust", TestEnum::LanguageName),
    Data::new("language.speakers", var!("language.speakers"), "Estimated number of fluent speakers", "1M", TestEnum::LanguageSpeakers),
    Data::new("language.family", var!("language.family"), "Language family the language belongs to", "prog", TestEnum::LanguageFamily),
    Data::new("language.script", var!("language.script"), "Writing script used by the language", "latin", TestEnum::LanguageScript),
    Data::new("currency.code", var!("currency.code"), "Three letter ISO code for the currency", "USD", TestEnum::CurrencyCode),
    Data::new("currency.name", var!("currency.name"), "Common name of the issued currency", "Dollar", TestEnum::CurrencyName),
    Data::new("currency.symbol", var!("currency.symbol"), "Display symbol used for the currency", "$", TestEnum::CurrencySymbol),
    Data::new("currency.country", var!("currency.country"), "Country issuing this currency officially", "US", TestEnum::CurrencyCountry),
    Data::new("repository.name", var!("repository.name"), "Display name of the source repository", "linux", TestEnum::RepositoryName),
    Data::new("repository.owner", var!("repository.owner"), "Owner account of the source repository", "torv", TestEnum::RepositoryOwner),
    Data::new("repository.stars", var!("repository.stars"), "Total stars received by repository", "99k", TestEnum::RepositoryStars),
    Data::new("repository.language", var!("repository.language"), "Primary programming language of repo", "C", TestEnum::RepositoryLanguage),
    Data::new("commit.hash", var!("commit.hash"), "Short hash identifier of the commit", "abc1234", TestEnum::CommitHash),
    Data::new("commit.author", var!("commit.author"), "Author name attached to the commit", "linus", TestEnum::CommitAuthor),
    Data::new("commit.message", var!("commit.message"), "Short commit message describing change", "fix bug", TestEnum::CommitMessage),
    Data::new("commit.date", var!("commit.date"), "Date when the commit was authored", "2024", TestEnum::CommitDate),
    Data::new("branch.name", var!("branch.name"), "Display name of the source branch", "main", TestEnum::BranchName),
    Data::new("branch.ahead", var!("branch.ahead"), "Commits ahead of the base branch", "3", TestEnum::BranchAhead),
    Data::new("branch.behind", var!("branch.behind"), "Commits behind the base branch", "0", TestEnum::BranchBehind),
    Data::new("contact.name", var!("contact.name"), "Full name of the stored contact", "Jane", TestEnum::ContactName),
    Data::new("contact.phone", var!("contact.phone"), "Primary phone number of the contact", "555-1111", TestEnum::ContactPhone),
    Data::new("contact.email", var!("contact.email"), "Primary email address of the contact", "j@x.io", TestEnum::ContactEmail),
    Data::new("contact.group", var!("contact.group"), "Contact group label assigned by user", "family", TestEnum::ContactGroup),
    Data::new("contact.notes", var!("contact.notes"), "Free form notes attached to the contact", "vip", TestEnum::ContactNotes),
    Data::new("contact.favorite", var!("contact.favorite"), "Whether the contact is marked favorite", "true", TestEnum::ContactFavorite),
    Data::new("contact.birthday", var!("contact.birthday"), "Birthday date stored for the contact", "01-01", TestEnum::ContactBirthday),
];    
