use varmap::*;
pub trait TestTrait {
    const NAME: &'static str;
    const DESCRIPTION: &'static str;
    fn init()->Self;
    fn run_test(&mut self, count: usize);
}

pub struct Data {
    pub var_name: &'static str,
    pub var_name_hash: varmap::Key,
    pub large_str_value: &'static str,
    pub small_str_value: &'static str,
    pub numeric_value: u32,
}
impl Data {
    const fn new(var_name: &'static str, key: varmap::Key, large_str_value: &'static str, small_str_value: &'static str, numeric_value: u32) -> Self {
        Self {
            var_name,
            var_name_hash: key,
            large_str_value,
            small_str_value,
            numeric_value,
        }
    }
}


pub(crate) const SMALL_SET: &[Data] = &[
    Data::new("object.name", var!("object.name"), "John the greatest Rust programmer", "John", 1),
    Data::new("user.name", var!("user.name"), "The full legal name of the user account holder", "Alice", 2),
    Data::new("user.email", var!("user.email"), "The primary contact email address for the user", "a@b.co", 3),
    Data::new("user.age", var!("user.age"), "Age of the user in years since their birth", "32", 4),
    Data::new("user.city", var!("user.city"), "The city where the user currently resides today", "Paris", 5),
    Data::new("user.country", var!("user.country"), "Country of origin or current residency of user", "France", 6),
    Data::new("user.phone", var!("user.phone"), "Primary mobile phone number including country code", "555-0100", 7),
    Data::new("user.role", var!("user.role"), "The assigned role or permission level of user", "admin", 8),
    Data::new("user.status", var!("user.status"), "Current account activity status of the user", "active", 9),
    Data::new("user.score", var!("user.score"), "Reputation or trust score assigned to user", "987", 10),
    Data::new("user.level", var!("user.level"), "Experience or progression level of the user", "42", 11),
    Data::new("user.bio", var!("user.bio"), "Short biographical text written by the user", "hi", 12),
    Data::new("user.avatar", var!("user.avatar"), "URL pointing to the user profile picture", "p.png", 13),
    Data::new("user.joined", var!("user.joined"), "Timestamp when user first joined the platform", "2020", 14),
    Data::new("user.locale", var!("user.locale"), "Preferred language and region setting for user", "en-US", 15),
    Data::new("user.zip", var!("user.zip"), "Postal or zip code for user mailing address", "10001", 16),
    Data::new("product.title", var!("product.title"), "The display title or name of the product item", "Widget", 17),
    Data::new("product.price", var!("product.price"), "Current retail price of the product in cents", "1999", 18),
    Data::new("product.stock", var!("product.stock"), "Number of units currently available in stock", "150", 19),
    Data::new("product.sku", var!("product.sku"), "Stock keeping unit identifier for the product", "SKU-001", 20),
    Data::new("product.brand", var!("product.brand"), "The brand or manufacturer of the product", "Acme", 21),
    Data::new("product.category", var!("product.category"), "Top level category this product belongs to", "tools", 22),
    Data::new("product.weight", var!("product.weight"), "Weight of the product measured in grams", "250", 23),
    Data::new("product.color", var!("product.color"), "Primary color of the product variant", "red", 24),
    Data::new("product.size", var!("product.size"), "Physical size designation of the product", "M", 25),
    Data::new("product.rating", var!("product.rating"), "Average customer rating from one to five", "4.5", 26),
    Data::new("product.reviews", var!("product.reviews"), "Total number of customer reviews submitted", "1024", 27),
    Data::new("product.vendor", var!("product.vendor"), "Name of the third party vendor selling it", "ShopCo", 28),
    Data::new("product.warranty", var!("product.warranty"), "Length of warranty coverage in months", "24", 29),
    Data::new("order.id", var!("order.id"), "Unique identifier assigned to this order record", "ORD-9", 30),
    Data::new("order.total", var!("order.total"), "Total amount charged for the entire order", "5000", 31),
    Data::new("order.status", var!("order.status"), "Current fulfillment status of the order", "shipped", 32),
    Data::new("order.date", var!("order.date"), "Date when the order was originally placed", "2024", 33),
    Data::new("order.customer", var!("order.customer"), "Customer name associated with the order", "Bob", 34),
    Data::new("order.shipping", var!("order.shipping"), "Selected shipping method for this order", "express", 35),
    Data::new("order.tracking", var!("order.tracking"), "Carrier tracking number for the shipment", "TRK123", 36),
    Data::new("order.tax", var!("order.tax"), "Tax amount calculated for the order", "400", 37),
    Data::new("order.discount", var!("order.discount"), "Discount amount applied to the order", "100", 38),
    Data::new("order.currency", var!("order.currency"), "Currency code used for the transaction", "USD", 39),
    Data::new("order.items", var!("order.items"), "Number of distinct items in the order", "3", 40),
    Data::new("device.model", var!("device.model"), "Manufacturer model name of the device", "Pixel", 41),
    Data::new("device.os", var!("device.os"), "Operating system running on the device", "Linux", 42),
    Data::new("device.version", var!("device.version"), "Firmware or software version of device", "1.2.3", 43),
    Data::new("device.battery", var!("device.battery"), "Current battery charge percentage level", "87", 44),
    Data::new("device.serial", var!("device.serial"), "Serial number printed on device chassis", "SN-001", 45),
    Data::new("device.vendor", var!("device.vendor"), "Vendor or manufacturer name of device", "Google", 46),
    Data::new("device.uptime", var!("device.uptime"), "Total seconds since device last booted", "3600", 47),
    Data::new("device.memory", var!("device.memory"), "Installed memory capacity in megabytes", "8192", 48),
    Data::new("device.storage", var!("device.storage"), "Total storage capacity in gigabytes", "256", 49),
    Data::new("device.cpu", var!("device.cpu"), "Central processor model designation", "ARM", 50),
    Data::new("device.temp", var!("device.temp"), "Current internal temperature in celsius", "42", 51),
    Data::new("server.host", var!("server.host"), "Hostname or fully qualified domain name", "api.io", 52),
    Data::new("server.port", var!("server.port"), "Network port number the server listens on", "8080", 53),
    Data::new("server.region", var!("server.region"), "Geographic region where server is hosted", "us-east", 54),
    Data::new("server.uptime", var!("server.uptime"), "Continuous uptime duration in seconds", "99999", 55),
    Data::new("server.load", var!("server.load"), "Current average system load percentage", "65", 56),
    Data::new("server.cores", var!("server.cores"), "Number of CPU cores available on host", "16", 57),
    Data::new("server.ram", var!("server.ram"), "Total RAM available on the server", "64GB", 58),
    Data::new("server.disk", var!("server.disk"), "Disk space used as a percentage value", "78", 59),
    Data::new("server.status", var!("server.status"), "Current health status reported by server", "ok", 60),
    Data::new("server.kernel", var!("server.kernel"), "Linux kernel version running on host", "6.1", 61),
    Data::new("file.path", var!("file.path"), "Absolute filesystem path to the file resource", "/tmp/a", 62),
    Data::new("file.size", var!("file.size"), "Size of the file measured in bytes", "1024", 63),
    Data::new("file.owner", var!("file.owner"), "Username of the file system owner", "root", 64),
    Data::new("file.perms", var!("file.perms"), "Octal permission bits set on the file", "0755", 65),
    Data::new("file.mtime", var!("file.mtime"), "Last modification time stored on the file", "2024", 66),
    Data::new("file.ext", var!("file.ext"), "File extension indicating the format type", "txt", 67),
    Data::new("file.mime", var!("file.mime"), "MIME type identifier for the file content", "text", 68),
    Data::new("file.hash", var!("file.hash"), "Hexadecimal hash digest of file contents", "abc123", 69),
    Data::new("file.encoding", var!("file.encoding"), "Character encoding used in the text file", "utf8", 70),
    Data::new("session.token", var!("session.token"), "Authentication token issued for the session", "tok-x", 71),
    Data::new("session.expires", var!("session.expires"), "Unix timestamp when the session expires", "9999", 72),
    Data::new("session.ip", var!("session.ip"), "Client IP address recorded for session", "1.2.3.4", 73),
    Data::new("session.agent", var!("session.agent"), "User agent string sent by the client", "curl", 74),
    Data::new("session.created", var!("session.created"), "Timestamp when this session was created", "1000", 75),
    Data::new("session.active", var!("session.active"), "Boolean flag whether session is active", "true", 76),
    Data::new("event.type", var!("event.type"), "The category or type designation of event", "click", 77),
    Data::new("event.source", var!("event.source"), "The originating source emitting the event", "web", 78),
    Data::new("event.payload", var!("event.payload"), "Data payload associated with the event", "{}", 79),
    Data::new("event.severity", var!("event.severity"), "Severity level assigned to the event", "info", 80),
    Data::new("event.channel", var!("event.channel"), "Channel through which event was delivered", "ws", 81),
    Data::new("event.retries", var!("event.retries"), "Number of retry attempts for the event", "0", 82),
    Data::new("config.key", var!("config.key"), "Configuration key identifying the setting", "k1", 83),
    Data::new("config.value", var!("config.value"), "Stored value associated with the key", "v1", 84),
    Data::new("config.scope", var!("config.scope"), "Scope where this configuration applies", "global", 85),
    Data::new("config.default", var!("config.default"), "Default fallback value for this setting", "off", 86),
    Data::new("config.env", var!("config.env"), "Environment where config is currently active", "prod", 87),
    Data::new("metric.name", var!("metric.name"), "Identifier name of the recorded metric", "cpu", 88),
    Data::new("metric.value", var!("metric.value"), "Numeric value of the metric sample", "42.5", 89),
    Data::new("metric.unit", var!("metric.unit"), "Unit of measurement for the metric", "ms", 90),
    Data::new("metric.tag", var!("metric.tag"), "Tag attached to the metric for grouping", "web", 91),
    Data::new("metric.bucket", var!("metric.bucket"), "Histogram bucket the value falls into", "10", 92),
    Data::new("log.level", var!("log.level"), "Severity level of the log entry record", "warn", 93),
    Data::new("log.message", var!("log.message"), "Human readable message text of the log", "oops", 94),
    Data::new("log.source", var!("log.source"), "Source module that emitted the log", "core", 95),
    Data::new("log.trace", var!("log.trace"), "Trace identifier linking related logs", "tr-1", 96),
    Data::new("network.ip", var!("network.ip"), "Internet protocol address of the interface", "10.0.0.1", 97),
    Data::new("network.mac", var!("network.mac"), "Hardware MAC address of network adapter", "AA:BB", 98),
    Data::new("network.gateway", var!("network.gateway"), "Default gateway address for the network", "10.0.0.1", 99),
    Data::new("network.dns", var!("network.dns"), "Primary DNS resolver address used", "8.8.8.8", 100),
    Data::new("network.subnet", var!("network.subnet"), "Subnet mask applied to the interface", "24", 101),
    Data::new("database.host", var!("database.host"), "Database server host where it is reachable", "db.io", 102),
    Data::new("database.name", var!("database.name"), "Logical name of the target database", "mydb", 103),
    Data::new("database.user", var!("database.user"), "Username used to authenticate to database", "dba", 104),
    Data::new("database.pool", var!("database.pool"), "Maximum size of the connection pool", "20", 105),
    Data::new("database.schema", var!("database.schema"), "Schema namespace used inside database", "pub", 106),
    Data::new("payment.method", var!("payment.method"), "Payment instrument used by the customer", "card", 107),
    Data::new("payment.amount", var!("payment.amount"), "Monetary amount charged in cents", "9999", 108),
    Data::new("payment.currency", var!("payment.currency"), "Three letter ISO currency code", "EUR", 109),
    Data::new("payment.status", var!("payment.status"), "Current state of payment processing", "ok", 110),
    Data::new("address.street", var!("address.street"), "Street name and number portion of address", "Main 1", 111),
    Data::new("address.city", var!("address.city"), "Name of the city portion of the address", "NYC", 112),
    Data::new("address.state", var!("address.state"), "State or province portion of the address", "NY", 113),
    Data::new("address.postal", var!("address.postal"), "Postal code portion of the address", "10001", 114),
    Data::new("company.name", var!("company.name"), "Registered legal name of the company", "Acme", 115),
    Data::new("company.domain", var!("company.domain"), "Primary web domain used by the company", "acme.io", 116),
    Data::new("company.size", var!("company.size"), "Approximate number of employees", "500", 117),
    Data::new("company.industry", var!("company.industry"), "Industry vertical the company operates in", "tech", 118),
    Data::new("vehicle.make", var!("vehicle.make"), "Manufacturer brand of the vehicle", "Honda", 119),
    Data::new("vehicle.model", var!("vehicle.model"), "Model designation of the vehicle", "Civic", 120),
    Data::new("vehicle.year", var!("vehicle.year"), "Model year of the vehicle production", "2020", 121),
    Data::new("vehicle.plate", var!("vehicle.plate"), "License plate number of the vehicle", "ABC123", 122),
    Data::new("vehicle.vin", var!("vehicle.vin"), "Vehicle identification number assigned", "VIN-X", 123),
    Data::new("book.title", var!("book.title"), "Full title of the published book", "Rust", 124),
    Data::new("book.author", var!("book.author"), "Primary author name of the book", "Klabnik", 125),
    Data::new("book.isbn", var!("book.isbn"), "ISBN identifier code for the book", "978-1", 126),
    Data::new("book.pages", var!("book.pages"), "Total number of pages in the book", "500", 127),
    Data::new("course.title", var!("course.title"), "Full title of the educational course", "Algo", 128),
    Data::new("course.instructor", var!("course.instructor"), "Name of the course primary instructor", "Tao", 129),
    Data::new("course.duration", var!("course.duration"), "Total duration of the course in hours", "40", 130),
    Data::new("course.difficulty", var!("course.difficulty"), "Difficulty level rating of the course", "hard", 131),
    Data::new("task.title", var!("task.title"), "Short title summarizing the task work", "fix", 132),
    Data::new("task.priority", var!("task.priority"), "Priority designation assigned to task", "high", 133),
    Data::new("task.assignee", var!("task.assignee"), "Person currently assigned to the task", "ann", 134),
    Data::new("task.deadline", var!("task.deadline"), "Date by which task must be completed", "2025", 135),
    Data::new("ticket.subject", var!("ticket.subject"), "Brief subject line for the support ticket", "bug", 136),
    Data::new("ticket.severity", var!("ticket.severity"), "Severity classification of the ticket", "p1", 137),
    Data::new("ticket.reporter", var!("ticket.reporter"), "User who reported the original ticket", "joe", 138),
    Data::new("post.title", var!("post.title"), "Display title of the published post", "Hello", 139),
    Data::new("post.author", var!("post.author"), "Author who wrote the post content", "bob", 140),
    Data::new("post.likes", var!("post.likes"), "Total count of likes received by post", "42", 141),
    Data::new("post.tags", var!("post.tags"), "Comma separated list of post tags", "rust", 142),
    Data::new("video.title", var!("video.title"), "Display title of the video content", "Demo", 143),
    Data::new("video.duration", var!("video.duration"), "Total duration of the video in seconds", "120", 144),
    Data::new("video.views", var!("video.views"), "Total view count accumulated by video", "1000", 145),
    Data::new("video.codec", var!("video.codec"), "Video codec used for encoding stream", "h264", 146),
    Data::new("image.width", var!("image.width"), "Width of the image measured in pixels", "1920", 147),
    Data::new("image.height", var!("image.height"), "Height of the image measured in pixels", "1080", 148),
    Data::new("image.format", var!("image.format"), "Image format extension used to encode", "png", 149),
    Data::new("image.alt", var!("image.alt"), "Alternative text describing the image", "logo", 150),
    Data::new("audio.title", var!("audio.title"), "Title of the audio track recording", "Song", 151),
    Data::new("audio.artist", var!("audio.artist"), "Artist or performer of the audio", "Bach", 152),
    Data::new("audio.bitrate", var!("audio.bitrate"), "Bitrate of the audio stream in kbps", "320", 153),
    Data::new("project.name", var!("project.name"), "Display name of the active project", "Apollo", 154),
    Data::new("project.owner", var!("project.owner"), "Owner responsible for the project", "lead", 155),
    Data::new("project.budget", var!("project.budget"), "Allocated budget for the project in usd", "50000", 156),
    Data::new("invoice.number", var!("invoice.number"), "Sequential invoice number identifier", "INV-1", 157),
    Data::new("invoice.due", var!("invoice.due"), "Date when the invoice payment is due", "2025", 158),
    Data::new("invoice.amount", var!("invoice.amount"), "Total amount due on the invoice", "1500", 159),
    Data::new("subscription.plan", var!("subscription.plan"), "Tier name of the subscription plan", "pro", 160),
    Data::new("subscription.renewal", var!("subscription.renewal"), "Date when subscription renews automatically", "2025", 161),
    Data::new("subscription.price", var!("subscription.price"), "Monthly price of the subscription plan", "29", 162),
    Data::new("notification.title", var!("notification.title"), "Short title displayed on notification", "alert", 163),
    Data::new("notification.body", var!("notification.body"), "Body text content of the notification", "look", 164),
    Data::new("notification.read", var!("notification.read"), "Whether the notification has been read", "false", 165),
    Data::new("comment.text", var!("comment.text"), "Full text body of the user comment", "nice", 166),
    Data::new("comment.author", var!("comment.author"), "Author name attached to the comment", "kim", 167),
    Data::new("review.title", var!("review.title"), "Headline title of the customer review", "good", 168),
    Data::new("review.stars", var!("review.stars"), "Star rating value given in the review", "5", 169),
    Data::new("review.body", var!("review.body"), "Detailed body text of the customer review", "ok", 170),
    Data::new("game.title", var!("game.title"), "Display title of the video game release", "Tetris", 171),
    Data::new("game.genre", var!("game.genre"), "Primary gameplay genre of the game title", "puzzle", 172),
    Data::new("game.publisher", var!("game.publisher"), "Company publishing the game commercially", "Sega", 173),
    Data::new("game.rating", var!("game.rating"), "Age rating assigned to the game content", "E", 174),
    Data::new("game.platform", var!("game.platform"), "Target platform the game runs on", "PC", 175),
    Data::new("movie.title", var!("movie.title"), "Display title of the released motion picture", "Heat", 176),
    Data::new("movie.director", var!("movie.director"), "Director who directed the motion picture", "Mann", 177),
    Data::new("movie.runtime", var!("movie.runtime"), "Total runtime of the movie in minutes", "170", 178),
    Data::new("movie.genre", var!("movie.genre"), "Primary genre classification of the movie", "crime", 179),
    Data::new("movie.year", var!("movie.year"), "Release year of the motion picture", "1995", 180),
    Data::new("song.title", var!("song.title"), "Title of the recorded musical track", "Yesterday", 181),
    Data::new("song.album", var!("song.album"), "Album on which the song appears", "Help", 182),
    Data::new("song.genre", var!("song.genre"), "Musical genre classification of the song", "rock", 183),
    Data::new("song.year", var!("song.year"), "Year the song was originally released", "1965", 184),
    Data::new("city.name", var!("city.name"), "Common name of the populated city area", "Tokyo", 185),
    Data::new("city.population", var!("city.population"), "Total population count of the city", "13M", 186),
    Data::new("city.country", var!("city.country"), "Country in which the city is located", "Japan", 187),
    Data::new("city.area", var!("city.area"), "Geographic area of the city in km2", "2194", 188),
    Data::new("city.timezone", var!("city.timezone"), "Local timezone identifier used by city", "JST", 189),
    Data::new("country.name", var!("country.name"), "Common short name of the country", "Japan", 190),
    Data::new("country.capital", var!("country.capital"), "Capital city of the named country", "Tokyo", 191),
    Data::new("country.population", var!("country.population"), "Total population of the country", "125M", 192),
    Data::new("country.language", var!("country.language"), "Primary official language of country", "ja", 193),
    Data::new("country.currency", var!("country.currency"), "Official currency used in the country", "JPY", 194),
    Data::new("flight.number", var!("flight.number"), "Flight number identifier assigned by carrier", "AA100", 195),
    Data::new("flight.origin", var!("flight.origin"), "Origin airport code for the flight", "JFK", 196),
    Data::new("flight.destination", var!("flight.destination"), "Destination airport code for the flight", "LAX", 197),
    Data::new("flight.departure", var!("flight.departure"), "Scheduled departure time for the flight", "08:00", 198),
    Data::new("flight.airline", var!("flight.airline"), "Operating airline carrier of the flight", "AA", 199),
    Data::new("hotel.name", var!("hotel.name"), "Display name of the hotel property", "Hilton", 200),
    Data::new("hotel.stars", var!("hotel.stars"), "Star rating assigned to the hotel", "5", 201),
    Data::new("hotel.rooms", var!("hotel.rooms"), "Total number of rooms in the hotel", "200", 202),
    Data::new("hotel.city", var!("hotel.city"), "City in which the hotel is located", "Rome", 203),
    Data::new("restaurant.name", var!("restaurant.name"), "Display name of the restaurant venue", "Nobu", 204),
    Data::new("restaurant.cuisine", var!("restaurant.cuisine"), "Primary cuisine style served at venue", "sushi", 205),
    Data::new("restaurant.price", var!("restaurant.price"), "Average price range per person served", "$$$", 206),
    Data::new("restaurant.hours", var!("restaurant.hours"), "Operating hours of the restaurant venue", "9-22", 207),
    Data::new("recipe.name", var!("recipe.name"), "Display name of the prepared dish", "Pizza", 208),
    Data::new("recipe.servings", var!("recipe.servings"), "Number of servings produced by recipe", "4", 209),
    Data::new("recipe.time", var!("recipe.time"), "Total time required to prepare recipe", "30m", 210),
    Data::new("recipe.difficulty", var!("recipe.difficulty"), "Difficulty level of preparing the recipe", "easy", 211),
    Data::new("workout.name", var!("workout.name"), "Display name of the workout routine", "Squats", 212),
    Data::new("workout.duration", var!("workout.duration"), "Total duration of the workout in minutes", "45", 213),
    Data::new("workout.calories", var!("workout.calories"), "Estimated calories burned during workout", "300", 214),
    Data::new("workout.intensity", var!("workout.intensity"), "Intensity level of the workout session", "high", 215),
    Data::new("plant.name", var!("plant.name"), "Common name of the plant species", "Cactus", 216),
    Data::new("plant.species", var!("plant.species"), "Scientific species name of the plant", "Cact", 217),
    Data::new("plant.watering", var!("plant.watering"), "Watering frequency required by the plant", "weekly", 218),
    Data::new("plant.sunlight", var!("plant.sunlight"), "Sunlight exposure requirement for plant", "full", 219),
    Data::new("animal.name", var!("animal.name"), "Common name of the animal species", "Cat", 220),
    Data::new("animal.species", var!("animal.species"), "Scientific species name of the animal", "Felis", 221),
    Data::new("animal.habitat", var!("animal.habitat"), "Natural habitat where animal is found", "home", 222),
    Data::new("animal.diet", var!("animal.diet"), "Primary dietary classification of animal", "carn", 223),
    Data::new("planet.name", var!("planet.name"), "Common name of the planet body", "Earth", 224),
    Data::new("planet.mass", var!("planet.mass"), "Total mass of the planet in kg", "6e24", 225),
    Data::new("planet.radius", var!("planet.radius"), "Equatorial radius of the planet in km", "6371", 226),
    Data::new("planet.moons", var!("planet.moons"), "Number of natural moons orbiting planet", "1", 227),
    Data::new("element.symbol", var!("element.symbol"), "Chemical symbol of the element", "H", 228),
    Data::new("element.name", var!("element.name"), "Common name of the chemical element", "Hydro", 229),
    Data::new("element.number", var!("element.number"), "Atomic number of the chemical element", "1", 230),
    Data::new("element.weight", var!("element.weight"), "Standard atomic weight of the element", "1.008", 231),
    Data::new("language.name", var!("language.name"), "Common name of the spoken language", "Rust", 232),
    Data::new("language.speakers", var!("language.speakers"), "Estimated number of fluent speakers", "1M", 233),
    Data::new("language.family", var!("language.family"), "Language family the language belongs to", "prog", 234),
    Data::new("language.script", var!("language.script"), "Writing script used by the language", "latin", 235),
    Data::new("currency.code", var!("currency.code"), "Three letter ISO code for the currency", "USD", 236),
    Data::new("currency.name", var!("currency.name"), "Common name of the issued currency", "Dollar", 237),
    Data::new("currency.symbol", var!("currency.symbol"), "Display symbol used for the currency", "$", 238),
    Data::new("currency.country", var!("currency.country"), "Country issuing this currency officially", "US", 239),
    Data::new("repository.name", var!("repository.name"), "Display name of the source repository", "linux", 240),
    Data::new("repository.owner", var!("repository.owner"), "Owner account of the source repository", "torv", 241),
    Data::new("repository.stars", var!("repository.stars"), "Total stars received by repository", "99k", 242),
    Data::new("repository.language", var!("repository.language"), "Primary programming language of repo", "C", 243),
    Data::new("commit.hash", var!("commit.hash"), "Short hash identifier of the commit", "abc1234", 244),
    Data::new("commit.author", var!("commit.author"), "Author name attached to the commit", "linus", 245),
    Data::new("commit.message", var!("commit.message"), "Short commit message describing change", "fix bug", 246),
    Data::new("commit.date", var!("commit.date"), "Date when the commit was authored", "2024", 247),
    Data::new("branch.name", var!("branch.name"), "Display name of the source branch", "main", 248),
    Data::new("branch.ahead", var!("branch.ahead"), "Commits ahead of the base branch", "3", 249),
    Data::new("branch.behind", var!("branch.behind"), "Commits behind the base branch", "0", 250),
    Data::new("contact.name", var!("contact.name"), "Full name of the stored contact", "Jane", 251),
    Data::new("contact.phone", var!("contact.phone"), "Primary phone number of the contact", "555-1111", 252),
    Data::new("contact.email", var!("contact.email"), "Primary email address of the contact", "j@x.io", 253),
    Data::new("contact.group", var!("contact.group"), "Contact group label assigned by user", "family", 254),
    Data::new("contact.notes", var!("contact.notes"), "Free form notes attached to the contact", "vip", 255),
    Data::new("contact.favorite", var!("contact.favorite"), "Whether the contact is marked favorite", "true", 256),
    Data::new("contact.birthday", var!("contact.birthday"), "Birthday date stored for the contact", "01-01", 257),
];    
